apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

namespace: default

namePrefix: play-
commonLabels:
  app: example
  env: test

images:
  - name: containous/whoami
    newTag: v1.5.0

configMapGenerator:
  - name: foo-props
    literals:
      - VAR_FOO=bar
